backend = "glx";
vsync = true;

# Shadows
shadow = true;
shadow-radius = 18;
shadow-opacity = 0.55;
shadow-offset-x = -8;
shadow-offset-y = -8;
shadow-color = "#000000";

# Fading
fading = true;
fade-in-step = 0.025;
fade-out-step = 0.025;
fade-delta = 8;

# Rounded corners
corner-radius = 8;

# Blur
blur:
{
    method = "dual_kawase";
    strength = 4;
};

# Window rules
rules = (
    {
        match = "class_g = 'st-256color' && focused";
        opacity = 0.75;
        blur-background = true;
        shadow = true;
        corner-radius = 10;
    },

    {
        match = "class_g = 'st-256color' && !focused";
        opacity = 0.70;
        blur-background = true;
        shadow = true;
        corner-radius = 10;
    }
);

# Fullscreen
fullscreen = false;

# Performance
use-damage = true;

# Window opacity detection
detect-client-opacity = true;

# Rounded corner detection
detect-rounded-corners = true;
